<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5xU2WM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5xU2WM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ5xU2WM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ5xU2WM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ5xU2WM\App_KernelDevDebugContainer([
    'container.build_hash' => 'J5xU2WM',
    'container.build_id' => '25e63ee3',
    'container.build_time' => 1594852822,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5xU2WM');
