version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./build/nginx/Dockerfile
        container_name: symfony_nginx
        volumes:
            - ./app/:/var/www/app
        ports:
            - 8001:80
        networks:
            - symfony
        depends_on:
            - php  
    php:
        build:
            context: .
            dockerfile: ./build/php/Dockerfile
        container_name: symfony_php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/symfony_db?serverVersion=5.7
        volumes:
            - ./app/:/var/www/app
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0.21
        container_name: symfony_mysql
        security_opt:
            - seccomp:unconfined
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./app/scriptsSQL:/docker-entrypoint-initdb.d/:rw
            - ./mysql:/var/lib/mysql
        networks:
            - symfony
networks:
    symfony:
